"""C_TABLE.md: every catalog reaction with a stationary C glider as one
input, the C's fate, and the other products. Survivor shift = change of the
C's position (cells) and of its phase t0 (mod 7) between input and output
seed events; the C input sits at its seed event as given in the id line."""
import json
from query import LIB, sig

rows = json.load(open("reactions.json"))
L = ["# Reactions involving C1/C2/C3 (generated by ctable.py)", "",
     "Columns: reaction id | C input seed event | other input seed event |"
     " kind | C-family outputs (name, t0, x0) | all outputs", ""]
for r in rows:
    cs = [n for n in (r["X"], r["Y"]) if n in ("C1", "C2", "C3")]
    if not cs:
        continue
    cev = (0, 0) if r["X"] in cs else tuple(r["Y_event"])
    oev = tuple(r["Y_event"]) if r["X"] in cs else (0, 0)
    couts = [tuple(p) for p in r["products_base"] if p[0] in ("C1", "C2", "C3")]
    L.append(f"| {r['id']} | {cs[0]}@{cev} | {oev} | {r['kind']} | "
             f"{couts} | {sig(r['out_base'])} |")
open("C_TABLE.md", "w").write("\n".join(L) + "\n")
print(len(L) - 4, "rows")
