"""DISPLACEMENTS.md / displacements.json: for every clean crossing in the
catalog (both inputs come out, same types), each glider's input seed event,
output seed event, the raw event difference, and the canonical
displacement (dt, dx) with 0 <= dt < p obtained by moving the output
event along its own trajectory. A glider that did not interact would have
(dt, dx) = (0, 0). The intercept shift is dx - v*dt (cells, at t = 0)."""
import json
from query import LIB

rows = json.load(open("reactions.json"))
out = []
L = ["# Crossing displacements (generated by displacements.py)", "",
     "| reaction | glider | in event | out event | canonical (dt, dx) | "
     "intercept shift |", "|---|---|---|---|---|---|"]
for r in rows:
    if r["kind"] != "crossing":
        continue
    ins = {r["X"]: (0, 0), r["Y"]: tuple(r["Y_event"])}
    for name, t0, x0 in r["products"]:
        g = LIB.gliders[name]
        ti, xi = ins[name]
        dt, dx = t0 - ti, x0 - xi
        q = dt // g.p
        cdt, cdx = dt - q * g.p, dx - q * g.d
        shift = cdx - g.velocity * cdt
        rec = {"reaction": r["id"], "glider": name, "in": [ti, xi],
               "out": [t0, x0], "canonical": [cdt, cdx],
               "intercept_shift": str(shift)}
        out.append(rec)
        L.append(f"| {r['id']} | {name} | {(ti, xi)} | {(t0, x0)} | "
                 f"{(cdt, cdx)} | {shift} |")
json.dump(out, open("displacements.json", "w"), indent=0)
open("DISPLACEMENTS.md", "w").write("\n".join(L) + "\n")
print(len(out) // 2, "crossings")
