"""Queries over the collision catalog (collisions.json + gliders.json).

Event arithmetic. A glider seeded at (t0, x0) has period vector (p, d);
(t0, x0) and (t0 + p, x0 + d) are the same trajectory. `lateral(name, ev)`
is the trajectory's intercept x at t = 0, as a Fraction
(x0 - v * t0): two events lie on the same trajectory iff their intercepts
are equal AND their phases agree, i.e. (t0 mod p) equal after moving
along the trajectory. `shift(name, ev_in, ev_out)` = (dx intercept, dt
phase) between an input and an output of the same glider type:
dx = lateral(out) - lateral(in), and dt = the time delay of the output
relative to the input measured along the trajectory, reduced mod p... we
report both the intercept shift and the canonical events.

Usage: python query.py            (writes CATALOG.md and gadgets.json)
"""

import json
from collections import Counter, defaultdict
from fractions import Fraction

from library import Library, BASE_ORDER

LIB = Library.load()
ROWS = json.load(open("collisions.json"))


def lateral(name, t0, x0):
    g = LIB.gliders[name]
    return Fraction(x0) - g.velocity * t0


def expand(products):
    """Compound products -> base-glider events where a verified parse
    exists; others unchanged."""
    out = []
    for name, t0, x0 in products:
        g = LIB.gliders[name]
        if g.parts:
            for nm, pt, px in g.parts:
                pg = LIB.gliders[nm]
                t = t0 + pt
                tt = t % pg.p
                out.append((nm, tt, x0 + px - (t - tt) // pg.p * pg.d))
        else:
            out.append((name, t0, x0))
    return out


def sig(names):
    return " + ".join(names) if names else "(nothing)"


def is_base(name):
    return name in BASE_ORDER


def survivors(r):
    """Which inputs come out unchanged in type, and their intercept shift
    (cells, at equal phase class) relative to the input trajectory."""
    X, Y = r["X"], r["Y"]
    inputs = {X: (0, 0), Y: tuple(r["Y_event"])}
    out = {}
    for name, t0, x0 in r["products"]:
        if name in inputs and name not in out:
            ti, xi = inputs[name]
            out[name] = (lateral(name, t0, x0) - lateral(name, ti, xi),
                         (t0 - ti) % LIB.gliders[name].p)
    return out


def reaction_rows():
    rows = []
    for r in ROWS:
        names = [p[0] for p in r["products"]]
        ex = expand(r["products"])
        rows.append({
            "id": f"{r['X']}+{r['Y']}#{r['cls']}",
            "X": r["X"], "Y": r["Y"], "cls": r["cls"],
            "Y_event": r["Y_event"], "kind": r["kind"], "T": r["T"],
            "products": r["products"], "products_base": ex,
            "out": names, "out_base": [e[0] for e in ex],
            "survivors": {k: [str(v[0]), v[1]] for k, v in survivors(r).items()},
        })
    return rows


def gadgets(rows):
    """Gadget-grade reaction lists."""
    G = defaultdict(list)
    for r in rows:
        X, Y, ob = r["X"], r["Y"], r["out_base"]
        sv = r["survivors"]
        if r["kind"] == "annihilation":
            G["annihilation"].append(r["id"])
        if r["kind"] == "crossing":
            G["crossing"].append((r["id"], sv))
        # catalysis: one input survives with zero intercept shift and same
        # phase, the other is transformed
        for name, (dx, dt) in sv.items():
            if dx == "0" and dt == 0 and sorted(r["out"]) != sorted([X, Y]):
                G["catalysis(" + name + " unchanged)"].append(
                    (r["id"], sig(r["out"])))
        # conversion to a single base glider
        if len(ob) == 1 and is_base(ob[0]) and ob[0] not in (X, Y):
            G["conversion to one base glider"].append((r["id"], ob[0]))
        # fan-out: >= 3 outputs or 2 outputs none of which is an input
        if len(ob) >= 3 or (len(ob) == 2 and not set(ob) & {X, Y}):
            G["fan-out (>=2 new gliders)"].append((r["id"], sig(ob)))
        # reflection: an output moving opposite to X (X right-moving) or to
        # Y (Y left-moving), with the other input surviving
        vx, vy = LIB.gliders[X].velocity, LIB.gliders[Y].velocity
        for nm in ob:
            v = LIB.gliders[nm].velocity
            if vx > 0 and v < 0 and Y in sv:
                G["reflection of X (Y survives)"].append((r["id"], sig(r["out"])))
                break
            if vy < 0 and v > 0 and X in sv:
                G["reflection of Y (X survives)"].append((r["id"], sig(r["out"])))
                break
    return G


def main():
    rows = reaction_rows()
    json.dump(rows, open("reactions.json", "w"), indent=0)
    G = gadgets(rows)
    json.dump({k: v for k, v in G.items()}, open("gadgets.json", "w"),
              indent=1, default=str)
    lines = ["# Rule 110 pairwise collision catalog (generated by query.py)",
             "",
             f"{len(rows)} collisions; kinds: " +
             ", ".join(f"{k} {v}" for k, v in
                       Counter(r['kind'] for r in rows).most_common()),
             "",
             "Each line: X+Y#class : Y seed event (tY, xY) relative to X at "
             "(0,0) -> products (compound products expanded into base "
             "gliders where a parse valid at every phase exists).", ""]
    pair = None
    for r in rows:
        if (r["X"], r["Y"]) != pair:
            pair = (r["X"], r["Y"])
            lines += ["", f"## {pair[0]} + {pair[1]}", ""]
        s = sig(r["out"])
        if r["out_base"] != r["out"]:
            s += f"   [= {sig(r['out_base'])}]"
        lines.append(f"- {r['id']} Y@{tuple(r['Y_event'])}: {s}")
    lines += ["", "# Gadget lists", ""]
    for k, v in G.items():
        lines += [f"## {k} ({len(v)})", ""]
        lines += [f"- {x}" for x in v] + [""]
    open("CATALOG.md", "w").write("\n".join(lines) + "\n")
    for k, v in G.items():
        print(f"{k}: {len(v)}")


def find(inputs=(), contains=(), exact=None, kind=None):
    """Reactions whose inputs include all of `inputs` (glider names or
    name prefixes ending in '*'), whose base-expanded outputs contain the
    multiset `contains`, or equal the multiset `exact`, and of `kind`."""
    rows = json.load(open("reactions.json"))

    def has(name, pat):
        return name.startswith(pat[:-1]) if pat.endswith("*") else name == pat

    out = []
    for r in rows:
        ins = [r["X"], r["Y"]]
        if not all(any(has(i, p) for i in ins) for p in inputs):
            continue
        ob = Counter(r["out_base"])
        if contains and any(ob[c] < n for c, n in Counter(contains).items()):
            continue
        if exact is not None and ob != Counter(exact):
            continue
        if kind and r["kind"] != kind:
            continue
        out.append(r)
    return out


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", nargs="?", default="build", choices=["build", "find"])
    ap.add_argument("--inputs", default="", help="comma list, * suffix = prefix")
    ap.add_argument("--contains", default="", help="comma multiset of outputs")
    ap.add_argument("--exact", default=None, help="comma multiset; '' = nothing")
    ap.add_argument("--kind", default=None)
    a = ap.parse_args()
    if a.cmd == "build":
        main()
    else:
        sp = lambda s: [x for x in s.split(",") if x]
        rs = find(sp(a.inputs), sp(a.contains),
                  None if a.exact is None else sp(a.exact), a.kind)
        for r in rs:
            print(f"{r['id']}  Y@{tuple(r['Y_event'])}  {r['kind']}: "
                  f"{sig(r['out'])}  products={r['products']}")
        print(len(rs), "reactions")
