"""Relay search in the catalog (architect's spec R).

A register cell holds C2 at seed event e. An A arriving from the left turns
it into C1 at e + DELTA (catalog reaction A+C2#0, single class, so DELTA is
exact and timing-free). A left-mover P then arrives from the right at a
fixed event. Because A only changes the ether on the LEFT of the cell, P's
side of the ether is identical in both scenarios, so for every class k of
(C2, P) the class k' of (C1, P) is well defined. We tabulate the pair of
outcomes (idle cell, set cell) for every P in the catalog, and flag:

  RELAY  : idle -> C2 + P unchanged (crossing) and set -> C2 at the SAME
           event as the idle case + a right-mover (+ P or not)
  READ   : outcomes differ in a clean way (both have at most 3 gliders)

Output: RELAY.md.
"""

import json
from collections import defaultdict

from collide import canonical_reps
from library import Library
from r110lib import class_key

LIB = Library.load()
ROWS = json.load(open("reactions.json"))
BY = defaultdict(dict)
for r in ROWS:
    BY[(r["X"], r["Y"])][r["cls"]] = r

# A + C2 -> C1: C2 seed (0, 53) relative to A; C1 product event
_ac2 = BY[("A", "C2")][0]
_c1 = [p for p in _ac2["products"] if p[0] == "C1"][0]
DELTA = (_c1[1] - _ac2["Y_event"][0], _c1[2] - _ac2["Y_event"][1])


def cls_of(X, Y, r):
    gx, gy = LIB.gliders[X], LIB.gliders[Y]
    PX, PY = (gx.p, gx.d), (gy.p, gy.d)
    keys = [class_key(rep, PX, PY) for rep in canonical_reps(LIB, X, Y)]
    k = class_key(r, PX, PY)
    return keys.index(k) if k in keys else None


def main():
    lines = ["# Relay / read table (generated by relay.py)", "",
             f"A + C2 -> C1 moves the cell's seed event by DELTA = {DELTA}.",
             "For each left-mover P and each class k of C2+P: the outcome on"
             " the idle cell (C2) and on the set cell (C1 at +DELTA), P at the"
             " same event. Events of C-products are relative to the idle "
             "cell's C2 seed event.", ""]
    flagged = []
    for (X, Y), classes in sorted(BY.items()):
        if X != "C2" or ("C1", Y) not in BY:
            continue
        for k, r in sorted(classes.items()):
            rep = r["Y_event"]
            r1 = (rep[0] - DELTA[0], rep[1] - DELTA[1])
            k1 = cls_of("C1", Y, r1)
            if k1 is None:
                raise AssertionError(f"{Y}: incompatible (should not happen)")
            s = BY[("C1", Y)][k1]
            # set case: C1 seeded at DELTA, P at the same absolute event
            # rep; predict() applies the lattice translation between rep
            # and the catalog representative of the C1+P class.
            from predict import predict, norm
            _, set_n = predict("C1", Y, r1, eX=DELTA)
            idle_n = sorted(norm(*p) for p in r["products"])
            set_ = set_n
            c2_idle = [p for p in idle_n if p[0] == "C2"]
            c2_set = [p for p in set_n if p[0] == "C2"]
            right = [p for p in set_n if LIB.gliders[p[0]].velocity > 0]
            tag = ""
            if (r["kind"] == "crossing" and c2_idle and c2_set
                    and c2_idle == c2_set and right):
                tag = "RELAY"
            elif r["out"] != s["out"] and len(idle_n) <= 3 and len(set_) <= 3:
                tag = "READ"
            line = (f"- {tag:5s} P={Y} C2-class {k} / C1-class {k1}: idle -> "
                    f"{' + '.join(r['out']) or '(nothing)'}; set -> "
                    f"{' + '.join(s['out']) or '(nothing)'}")
            if tag:
                flagged.append(line)
            lines.append(line)
    lines = lines[:6] + ["## Flagged", ""] + flagged + ["", "## All", ""] + lines[6:]
    open("RELAY.md", "w").write("\n".join(lines) + "\n")
    print("\n".join(flagged))


if __name__ == "__main__":
    main()
