"""Phase shifters and switches.

A crossing (or any reaction in which a glider T survives) moves T's seed
event by Delta = (out event) - (in event). Any later glider Z that would
have met T in collision class k now meets it in class pi(k), where pi is
the permutation of the (T, Z) classes induced by Delta. If the outcomes of
classes k and pi(k) differ, the earlier reaction acts as a *switch*: the
passage of S (the glider that shifted T) decides what Z does to T.

This script computes, for every catalog reaction with a surviving input T
(same type in and out), and for every partner Z with a catalog pair (T, Z)
or (Z, T), the induced class permutation and which classes change outcome.
Only like-for-like comparisons are made: if the shifted relative vector is
not ether-compatible (T's shift changed the ether between T and Z, which
happens when the shifter has nonzero slip), the pair is skipped.
Output: SWITCHES.md and switches.json.
"""

import json
from collections import defaultdict

from collide import canonical_reps
from library import Library, BASE_ORDER as BASE
from r110lib import class_key

LIB = Library.load()
ROWS = json.load(open("reactions.json"))
BY_PAIR = defaultdict(dict)
for r in ROWS:
    BY_PAIR[(r["X"], r["Y"])][r["cls"]] = r


def class_index(X, Y, r):
    """Index (as in the catalog) of the X-Y collision class of relative
    vector r = event(Y) - event(X)."""
    gx, gy = LIB.gliders[X], LIB.gliders[Y]
    PX, PY = (gx.p, gx.d), (gy.p, gy.d)
    reps = canonical_reps(LIB, X, Y)
    keys = [class_key(rep, PX, PY) for rep in reps]
    kr = class_key(r, PX, PY)
    return keys.index(kr) if kr in keys else None


def outcome(X, Y, k):
    return " + ".join(BY_PAIR[(X, Y)][k]["out"]) or "(nothing)"


def permutation(T, delta, Z):
    """Class permutation of the pair containing T and Z when T's seed event
    moves by delta. -> (pair, {k: k'}) or None if no catalog pair."""
    if (T, Z) in BY_PAIR:
        X, Y, sign = T, Z, -1      # r = eY - eX ; X moves -> r - delta
    elif (Z, T) in BY_PAIR:
        X, Y, sign = Z, T, +1
    else:
        return None
    reps = canonical_reps(LIB, X, Y)
    pi = {}
    for k, rep in enumerate(reps):
        r2 = (rep[0] + sign * delta[0], rep[1] + sign * delta[1])
        pi[k] = class_index(X, Y, r2)
        if pi[k] is None:
            # r2 is not ether-compatible: T's shift changed the ether on
            # Z's side (the shifter S has nonzero slip and ends up between
            # them in the lattice sense); no like-for-like comparison.
            return None
    return (X, Y), pi


def main():
    out = []
    lines = ["# Phase shifters and switches (generated by switches.py)", "",
             "For each clean shifter (a crossing, or an absorption) in which "
             "an input T survives (same glider type in and out), T's seed event moves by Delta. A later partner Z "
             "that would have met T in class k then meets it in class pi(k). "
             "Only partners with >= 2 classes can be affected; partners Z are base "
             "gliders and A^2..A^5, B^2, B^3. Listed: "
             "reactions whose pi is not the identity for some Z, with the "
             "outcome changes (k: outcome -> pi(k): outcome).", ""]
    simple = set(BASE) | {"A^2", "A^3", "A^4", "A^5", "B^2", "B^3"}
    for r in ROWS:
        X, Y = r["X"], r["Y"]
        if r["kind"] not in ("crossing", "absorption"):
            continue
        ins = {X: (0, 0), Y: tuple(r["Y_event"])}
        for T in dict.fromkeys((X, Y)):
            outs = [p for p in r["products"] if p[0] == T]
            if len(outs) != 1 or X == Y:
                continue
            e_in, e_out = ins[T], (outs[0][1], outs[0][2])
            delta = (e_out[0] - e_in[0], e_out[1] - e_in[1])
            for Z in sorted(simple):
                res = permutation(T, delta, Z)
                if res is None:
                    continue
                (PX, PY), pi = res
                changed = {k: v for k, v in pi.items() if k != v}
                if not changed:
                    continue
                diffs = [(k, v) for k, v in changed.items()
                         if outcome(PX, PY, k) != outcome(PX, PY, v)]
                rec = {"reaction": r["id"], "T": T, "delta": delta,
                       "pair": [PX, PY], "pi": pi,
                       "outcome_changes": diffs}
                out.append(rec)
                if diffs:
                    lines.append(f"- {r['id']} shifts {T} by {delta}; for "
                                 f"{PX}+{PY}: " + "; ".join(
                                     f"#{k} {outcome(PX, PY, k)} -> #{v} "
                                     f"{outcome(PX, PY, v)}"
                                     for k, v in diffs))
    json.dump(out, open("switches.json", "w"), indent=0)
    open("SWITCHES.md", "w").write("\n".join(lines) + "\n")
    print(len(out), "non-identity permutations;",
          sum(1 for o in out if o["outcome_changes"]), "with outcome changes")


if __name__ == "__main__":
    main()
