"""Write the body of both books in the order of Rationality: A-Z.

- annotated/main.tex: title page, contents, then book / sequence headings and every post
  that has both annotated/posts/<file>.tex and annotated/afterwords/<file>.tex.
- honest/honest.tex: everything above the "% ---- BODY" marker is kept as written by hand;
  below it, book / sequence headings and every honest/sections/<file>.tex that exists.

Order: data/manifests/rationality_az.json (books, sequences, posts), then a final part,
"Beyond the Sequences", with the seven earlier-annotated posts that are not in the
collection. A heading is written only if at least one of its posts is ready, so both
books can be built while the work is in progress.

Usage: python src/make_books.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANN = ROOT / "annotated"
HON = ROOT / "honest"
MARKER = "% ---- BODY: generated by src/make_books.py from here to the end; do not edit by hand ----\n"

# Posts annotated before the converter existed use shorter file names.
FILE_FOR_SLUG = {"making-beliefs-pay-rent-in-anticipated-experiences": "making-beliefs-pay-rent"}
BEYOND_TITLE = "Beyond the Sequences"
BEYOND = ["humans-are-not-automatically-strategic", "toolbox-thinking-and-law-thinking",
          "local-validity-as-a-key-to-sanity-and-civilization",
          "diseased-thinking-dissolving-questions-about-disease", "on-caring",
          "strong-evidence-is-common", "pr-is-corrosive"]

TITLE_PAGE = r"""\begin{document}

{\noindent\LARGE LessWrong, Annotated\par}\medskip
{\noindent\large Rationality: A--Z, and seven later posts, with marginal commentary\par}\bigskip

\begin{minipage}{0.6\textwidth}
\setlength{\parskip}{0.7\baselineskip}
The left column reproduces each post as published on LessWrong. Nothing has been changed except to convert web formatting to print: links become plain text, the authors' italics and bold stay as they were, and images are replaced by a link to the original. The numbered marks are mine.

The posts are those of \textsc{Rationality: A--Z}, in the order of the collection on LessWrong, grouped by its books and sequences. A last part adds seven later posts that LessWrong also features.

The right column holds my comments. Each starts with a tag:

\begin{itemize}
\item \textsc{paragraph}: marked at the start of a paragraph. What the paragraph as a whole is for, whether it does that job, and how it fits with the paragraphs around it.
\item \textsc{style}: the writing could be clearer or shorter. Many of these cite principles from Joseph Williams, \textsc{Style: Lessons in Clarity and Grace}: put the characters in the subjects and the actions in the verbs; put old information before new; save the end of a sentence for what matters most; cut hedges, intensifiers and redundant words.
\item \textsc{logic}: the argument has a gap, an unstated assumption, or a claim that goes beyond its support.
\item \textsc{fact}: a factual or arithmetic claim that is wrong, or that needs a source.
\item \textsc{cut}: the passage does no work and could go.
\end{itemize}

Each post ends with a Summary, and a Response that judges it as a whole.

This is a personal study copy. The posts belong to their authors.
\end{minipage}

\bigskip
\renewcommand{\contentsname}{Contents}
\tableofcontents
"""

HEADER = r"""% Annotated LessWrong posts. GENERATED by src/make_books.py; edit that script, not this file.
% Build: latexmk -pdf -outdir=build main.tex   (post files in posts/ are not in git; see README)
\input{preamble}
"""


def tex_escape(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#").replace("_", r"\_")


def outline() -> list:
    """[(book, sequence, [file names])] in reading order, then the final part."""
    manifest = json.loads((ROOT / "data/manifests/rationality_az.json").read_text())
    groups = []
    for e in manifest:
        key = (e["book"], e["section"])
        if not groups or groups[-1][:2] != key:
            groups.append((e["book"], e["section"], []))
        groups[-1][2].append(FILE_FOR_SLUG.get(e["slug"], e["slug"]))
    groups.append((BEYOND_TITLE, None, BEYOND))
    return groups


def body(ready) -> tuple[list, int, int]:
    lines, n, total, book = [], 0, 0, None
    for bk, seq, files in outline():
        total += len(files)
        have = [f for f in files if ready(f)]
        n += len(have)
        if not have:
            continue
        if bk != book:
            book = bk
            lines.append(f"\n\\bookhead{{{tex_escape(bk.strip())}}}")
        if seq:
            lines.append(f"\\sequencehead{{{tex_escape(seq.strip())}}}")
        lines.extend(have)
    return lines, n, total


def main() -> None:
    ann_ready = lambda f: (ANN / "posts" / f"{f}.tex").exists() and (ANN / "afterwords" / f"{f}.tex").exists()
    lines, n, total = body(ann_ready)
    out = [l if l.startswith(("\n", "\\")) else f"\\input{{posts/{l}}}\\closepost\n\\input{{afterwords/{l}}}"
           for l in lines]
    (ANN / "main.tex").write_text(HEADER + "\n" + TITLE_PAGE + "\n".join(out) + "\n\n\\end{document}\n")
    print(f"annotated/main.tex: {n} of {total} posts")

    hon_ready = lambda f: (HON / "sections" / f"{f}.tex").exists()
    lines, n, total = body(hon_ready)
    out = [l if l.startswith(("\n", "\\")) else f"\\input{{sections/{l}}}" for l in lines]
    text = (HON / "honest.tex").read_text()
    if MARKER not in text:
        raise SystemExit("honest/honest.tex has no BODY marker")
    head = text[:text.index(MARKER) + len(MARKER)]
    (HON / "honest.tex").write_text(head + "\n".join(out) + "\n\n\\end{document}\n")
    print(f"honest/honest.tex: {n} of {total} posts")


if __name__ == "__main__":
    main()
