"""Write annotated/main.tex: title page, contents, and every annotated post in order.

Order: the 50 "Highlights from the Sequences" in LessWrong's reading order, grouped
under their six sequence titles, then two Annual Review winners. A post is included
only if both annotated/posts/<file>.tex and annotated/afterwords/<file>.tex exist, so
the volume can be built while some posts are still in progress.

Usage: python src/make_main.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANN = ROOT / "annotated"

# Posts annotated before the converter existed use shorter file names.
FILE_FOR_SLUG = {"making-beliefs-pay-rent-in-anticipated-experiences": "making-beliefs-pay-rent"}
OTHER_POSTS = [("strong-evidence-is-common", "Strong Evidence is Common"),
               ("pr-is-corrosive", "“PR” is corrosive; “reputation” is not.")]

TITLE_PAGE = r"""\begin{document}

{\noindent\LARGE LessWrong, Annotated\par}\medskip
{\noindent\large The Highlights from the Sequences, and two later posts, with marginal commentary\par}\bigskip

\begin{minipage}{0.6\textwidth}
\setlength{\parskip}{0.7\baselineskip}
The left column reproduces each post as published on LessWrong. Nothing has been changed except to convert web formatting to print: links become plain text, the authors' italics and bold stay as they were, and images are replaced by a link to the original. The numbered marks are mine.

The posts are the fifty ``Highlights from the Sequences'' that LessWrong itself selected, in its reading order, followed by two winners of its Annual Review.

The right column holds my comments. Each starts with a tag:

\begin{itemize}
\item \textsc{paragraph}: marked at the start of a paragraph. What the paragraph as a whole is for, whether it does that job, and how it fits with the paragraphs around it.
\item \textsc{style}: the writing could be clearer or shorter. Many of these cite principles from Joseph Williams, \textsc{Style: Lessons in Clarity and Grace}: put the characters in the subjects and the actions in the verbs; put old information before new; save the end of a sentence for what matters most; cut hedges, intensifiers and redundant words.
\item \textsc{logic}: the argument has a gap, an unstated assumption, or a claim that goes beyond its support.
\item \textsc{fact}: a factual or arithmetic claim that is wrong, or that needs a source.
\item \textsc{cut}: the passage does no work and could go.
\end{itemize}

Each post ends with a Summary, and a Response that judges it as a whole.

This is a personal study copy. The posts belong to their authors.
\end{minipage}

\bigskip
\renewcommand{\contentsname}{Contents}
\tableofcontents
"""

HEADER = r"""% Annotated LessWrong posts. GENERATED by src/make_main.py; edit that script, not this file.
% Build: latexmk -pdf -outdir=build main.tex   (post files in posts/ are not in git; see README)
\input{preamble}
"""


def ready(name: str) -> bool:
    return (ANN / "posts" / f"{name}.tex").exists() and (ANN / "afterwords" / f"{name}.tex").exists()


def main() -> None:
    manifest = json.loads((ROOT / "data/manifests/highlights.json").read_text())
    body, included, missing, section = [], 0, [], None
    for e in manifest:
        name = FILE_FOR_SLUG.get(e["slug"], e["slug"])
        if e["section"] != section:
            section = e["section"]
            body.append(f"\n\\sequencehead{{{section}}}")
        if ready(name):
            body.append(f"\\input{{posts/{name}}}\\closepost\n\\input{{afterwords/{name}}}")
            included += 1
        else:
            missing.append(name)
    body.append("\n\\sequencehead{Two later posts: Annual Review winners}")
    for name, _ in OTHER_POSTS:
        if ready(name):
            body.append(f"\\input{{posts/{name}}}\\closepost\n\\input{{afterwords/{name}}}")
            included += 1
        else:
            missing.append(name)
    (ANN / "main.tex").write_text(HEADER + "\n" + TITLE_PAGE + "\n".join(body) + "\n\n\\end{document}\n")
    print(f"main.tex: {included} posts included, {len(missing)} not ready")
    for m in missing:
        print("  not ready:", m)


if __name__ == "__main__":
    main()
