"""U.S. Presidents data."""

PRESIDENTS = [
    {"number": 1, "name": "George Washington", "party": "None", "term": "1789-1797", "key_fact": "First president; set precedent of two-term limit."},
    {"number": 2, "name": "John Adams", "party": "Federalist", "term": "1797-1801", "key_fact": "First president to live in the White House."},
    {"number": 3, "name": "Thomas Jefferson", "party": "Democratic-Republican", "term": "1801-1809", "key_fact": "Authored the Declaration of Independence; Louisiana Purchase."},
    {"number": 4, "name": "James Madison", "party": "Democratic-Republican", "term": "1809-1817", "key_fact": "Father of the Constitution; led nation through War of 1812."},
    {"number": 5, "name": "James Monroe", "party": "Democratic-Republican", "term": "1817-1825", "key_fact": "Monroe Doctrine warned European powers against colonizing the Americas."},
    {"number": 6, "name": "John Quincy Adams", "party": "Democratic-Republican", "term": "1825-1829", "key_fact": "Son of John Adams; later served in the House of Representatives."},
    {"number": 7, "name": "Andrew Jackson", "party": "Democratic", "term": "1829-1837", "key_fact": "Populist president; Indian Removal Act."},
    {"number": 8, "name": "Martin Van Buren", "party": "Democratic", "term": "1837-1841", "key_fact": "Faced the Panic of 1837 economic crisis."},
    {"number": 9, "name": "William Henry Harrison", "party": "Whig", "term": "1841-1841", "key_fact": "Shortest presidency — died 31 days after inauguration."},
    {"number": 10, "name": "John Tyler", "party": "Whig", "term": "1841-1845", "key_fact": "First VP to assume presidency due to death of predecessor."},
    {"number": 11, "name": "James K. Polk", "party": "Democratic", "term": "1845-1849", "key_fact": "Oversaw Mexican-American War and westward expansion."},
    {"number": 12, "name": "Zachary Taylor", "party": "Whig", "term": "1849-1850", "key_fact": "War hero; died in office after 16 months."},
    {"number": 13, "name": "Millard Fillmore", "party": "Whig", "term": "1850-1853", "key_fact": "Signed the Compromise of 1850."},
    {"number": 14, "name": "Franklin Pierce", "party": "Democratic", "term": "1853-1857", "key_fact": "Kansas-Nebraska Act inflamed slavery tensions."},
    {"number": 15, "name": "James Buchanan", "party": "Democratic", "term": "1857-1861", "key_fact": "Presidency marked by drift toward Civil War."},
    {"number": 16, "name": "Abraham Lincoln", "party": "Republican", "term": "1861-1865", "key_fact": "Preserved the Union; Emancipation Proclamation; assassinated."},
    {"number": 17, "name": "Andrew Johnson", "party": "Democratic", "term": "1865-1869", "key_fact": "First president to be impeached."},
    {"number": 18, "name": "Ulysses S. Grant", "party": "Republican", "term": "1869-1877", "key_fact": "Civil War general; Reconstruction era president."},
    {"number": 19, "name": "Rutherford B. Hayes", "party": "Republican", "term": "1877-1881", "key_fact": "Won disputed 1876 election; ended Reconstruction."},
    {"number": 20, "name": "James A. Garfield", "party": "Republican", "term": "1881-1881", "key_fact": "Assassinated after less than 200 days in office."},
    {"number": 21, "name": "Chester A. Arthur", "party": "Republican", "term": "1881-1885", "key_fact": "Signed the Pendleton Civil Service Reform Act."},
    {"number": 22, "name": "Grover Cleveland", "party": "Democratic", "term": "1885-1889", "key_fact": "First Democrat elected after the Civil War."},
    {"number": 23, "name": "Benjamin Harrison", "party": "Republican", "term": "1889-1893", "key_fact": "Grandson of William Henry Harrison; Sherman Antitrust Act."},
    {"number": 24, "name": "Grover Cleveland", "party": "Democratic", "term": "1893-1897", "key_fact": "Only president to serve two non-consecutive terms."},
    {"number": 25, "name": "William McKinley", "party": "Republican", "term": "1897-1901", "key_fact": "Spanish-American War; assassinated in 1901."},
    {"number": 26, "name": "Theodore Roosevelt", "party": "Republican", "term": "1901-1909", "key_fact": "Trust-buster; Panama Canal; youngest president at 42."},
    {"number": 27, "name": "William Howard Taft", "party": "Republican", "term": "1909-1913", "key_fact": "Later served as Chief Justice of the Supreme Court."},
    {"number": 28, "name": "Woodrow Wilson", "party": "Democratic", "term": "1913-1921", "key_fact": "Led nation through WWI; championed League of Nations."},
    {"number": 29, "name": "Warren G. Harding", "party": "Republican", "term": "1921-1923", "key_fact": "Teapot Dome scandal; died in office."},
    {"number": 30, "name": "Calvin Coolidge", "party": "Republican", "term": "1923-1929", "key_fact": "Presided over the Roaring Twenties prosperity."},
    {"number": 31, "name": "Herbert Hoover", "party": "Republican", "term": "1929-1933", "key_fact": "Great Depression began during his presidency."},
    {"number": 32, "name": "Franklin D. Roosevelt", "party": "Democratic", "term": "1933-1945", "key_fact": "New Deal; led through WWII; only president elected four times."},
    {"number": 33, "name": "Harry S. Truman", "party": "Democratic", "term": "1945-1953", "key_fact": "Atomic bomb decision; Marshall Plan; Korean War."},
    {"number": 34, "name": "Dwight D. Eisenhower", "party": "Republican", "term": "1953-1961", "key_fact": "WWII Supreme Commander; Interstate Highway System."},
    {"number": 35, "name": "John F. Kennedy", "party": "Democratic", "term": "1961-1963", "key_fact": "Cuban Missile Crisis; assassinated in Dallas."},
    {"number": 36, "name": "Lyndon B. Johnson", "party": "Democratic", "term": "1963-1969", "key_fact": "Great Society programs; Civil Rights Act; Vietnam escalation."},
    {"number": 37, "name": "Richard Nixon", "party": "Republican", "term": "1969-1974", "key_fact": "Opened relations with China; resigned over Watergate."},
    {"number": 38, "name": "Gerald Ford", "party": "Republican", "term": "1974-1977", "key_fact": "Only president never elected president or vice president."},
    {"number": 39, "name": "Jimmy Carter", "party": "Democratic", "term": "1977-1981", "key_fact": "Camp David Accords; Nobel Peace Prize in 2002."},
    {"number": 40, "name": "Ronald Reagan", "party": "Republican", "term": "1981-1989", "key_fact": "Reaganomics; Cold War diplomacy; survived assassination attempt."},
    {"number": 41, "name": "George H. W. Bush", "party": "Republican", "term": "1989-1993", "key_fact": "Gulf War; end of the Cold War."},
    {"number": 42, "name": "Bill Clinton", "party": "Democratic", "term": "1993-2001", "key_fact": "Economic boom of the 1990s; impeached but acquitted."},
    {"number": 43, "name": "George W. Bush", "party": "Republican", "term": "2001-2009", "key_fact": "9/11 response; wars in Afghanistan and Iraq."},
    {"number": 44, "name": "Barack Obama", "party": "Democratic", "term": "2009-2017", "key_fact": "First African American president; Affordable Care Act."},
    {"number": 45, "name": "Donald Trump", "party": "Republican", "term": "2017-2021", "key_fact": "Impeached twice; first president with no prior political or military service."},
    {"number": 46, "name": "Joe Biden", "party": "Democratic", "term": "2021-2025", "key_fact": "Oldest president inaugurated at 78."},
    {"number": 47, "name": "Donald Trump", "party": "Republican", "term": "2025-present", "key_fact": "First president to serve two non-consecutive terms since Grover Cleveland."},
]
