#!/bin/bash
cd "$(dirname "$0")"
for spec in "JJJJJZZZZZZJJJJJZZZZZZJJJJJZZZZZZJJJJJZZZZZZ 12 15" "ZZZZZZZZZZZZ 12 15" "JJJZZZZJJJZZZZJJJZZZZJJJZZZZJJJZZZZJJJZZZZJJJZZZZJJJZZZZ 12 14" "JJJJJJZZZZZZZJJJJJJZZZZZZZJJJJJJZZZZZZZ 12 14"; do
  set -- $spec
  echo "=== $1"
  python3 plan_check.py $1 $2 $3
done
echo BATCH DONE
